import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // 1. lang="en"을 lang="ko"로 변경합니다. (선택 사항이지만 권장)
    <html lang="ko">
      
      {/* 2. 폰트 className을 다시 추가합니다. */}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        {/* 1. Header 컴포넌트 사용 */}
        <Header />

        {/* 2. 각 페이지의 내용이 들어갈 <main> 태그와 {children} */}
        <main className="max-w-7xl mx-auto p-4">
          {children}
        </main>

        {/* 3. Footer 컴포넌트 사용 */}
        <Footer />
        
      </body>
    </html>
  );
}
